application:
  actions: actions
  runtimeManifest:
    packages:
      maidenform-demo:
        actions:
          newsletter:
            function: actions/newsletter/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
              CAPTCHA_SITE_KEY: $CAPTCHA_SITE_KEY
              CAPTCHA_SECRET_KEY: $CAPTCHA_SECRET_KEY
              ZETA_PASSWORD: $ZETA_PASSWORD
              ZETA_SITE_ID: $ZETA_SITE_ID
            annotations:
              require-adobe-auth: false
              final: true
