name: Sync commerce products to Sitemap

on:
  schedule:
    # Run every day at 1:30am PT - 9:30 UTC
    - cron: '30 1 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/index-products
